In [1]:
import pandas as pd
import duckdb
from matplotlib import pyplot as plt
import numpy as np
from IPython.display import display

In [2]:
aisles=pd.read_csv(r'\Users\DELL\OneDrive\Desktop\docs\duck\aisles.csv')
aisles

     aisle_id                       aisle
0           1       prepared soups salads
1           2           specialty cheeses
2           3         energy granola bars
3           4               instant foods
4           5  marinades meat preparation
..        ...                         ...
129       130    hot cereal pancake mixes
130       131                   dry pasta
131       132                      beauty
132       133  muscles joints pain relief
133       134  specialty wines champagnes

[134 rows x 2 columns]

In [3]:
departments=pd.read_csv(r'\Users\DELL\OneDrive\Desktop\docs\duck\departments.csv')
departments

    department_id       department
0               1           frozen
1               2            other
2               3           bakery
3               4          produce
4               5          alcohol
5               6    international
6               7        beverages
7               8             pets
8               9  dry goods pasta
9              10             bulk
10             11    personal care
11             12     meat seafood
12             13           pantry
13             14        breakfast
14             15     canned goods
15             16       dairy eggs
16             17        household
17             18           babies
18             19           snacks
19             20             deli
20             21          missing

In [4]:
orders=pd.read_csv(r'\Users\DELL\OneDrive\Desktop\docs\duck\orders.csv')
orders

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0
...,...,...,...,...,...,...,...
3421078,2266710,206209,prior,10,5,18,29.0
3421079,1854736,206209,prior,11,4,10,30.0
3421080,626363,206209,prior,12,1,12,18.0
3421081,2977660,206209,prior,13,1,12,7.0
3421082,272231,206209,train,14,6,14,30.0

In [5]:
products=pd.read_csv(r'\Users\DELL\OneDrive\Desktop\docs\duck\products.csv')
products

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13
...,...,...,...,...
49683,49684,"Vodka, Triple Distilled, Twist of Vanilla",124,5
49684,49685,En Croute Roast Hazelnut Cranberry,42,1
49685,49686,Artisan Baguette,112,3
49686,49687,Smartblend Healthy Metabolism Dry Cat Food,41,8
49687,49688,Fresh Foaming Cleanser,73,11

In [6]:
v=pd.read_csv(r'\Users\DELL\OneDrive\Desktop\docs\duck\order_products__train.csv')
v

         order_id  product_id  add_to_cart_order  reordered
0               1       49302                  1          1
1               1       11109                  2          1
2               1       10246                  3          0
3               1       49683                  4          0
4               1       43633                  5          1
...           ...         ...                ...        ...
1384612   3421063       14233                  3          1
1384613   3421063       35548                  4          1
1384614   3421070       35951                  1          1
1384615   3421070       16953                  2          1
1384616   3421070        4724                  3          1

[1384617 rows x 4 columns]

In [7]:
import pandas as pd
import duckdb
from matplotlib import pyplot as plt
import numpy as np
from IPython.display import display

In [8]:
path = (r'\Users\DELL\OneDrive\Desktop\docs\duck\\')
aisles=pd.read_csv(path+"aisles.csv")
departments=pd.read_csv(path+"departments.csv")
orders=pd.read_csv(path+"orders.csv")
products=pd.read_csv(path+"products.csv")
order_products__train=pd.read_csv(path+"order_products__train.csv")
order_products__prior=pd.read_csv(path+"order_products__prior.csv")

  # 3. Display DataFrames
dfs = [aisles, departments, order_products__train, orders, products]
for df in dfs:
    display(df.head())

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13

Error
DuckDB only knows about tables explicitly registered or created.
I have d and v as pandas DataFrames, but DuckDB didn’t know them as SQL tables.

Once I register them, DuckDB can query them just like any other table.
import duckdb
import pandas as pd

# Load CSVs into pandas
d = pd.read_csv(r'\Users\DELL\OneDrive\Desktop\docs\duck\order_products__prior.csv')
v = pd.read_csv(r'\Users\DELL\OneDrive\Desktop\docs\duck\order_products__train.csv')
products = pd.read_csv(r'\Users\DELL\OneDrive\Desktop\docs\duck\products.csv')

# Register them as DuckDB tables
duckdb.register('order_products_prior', d)
duckdb.register('order_products_train', v)
duckdb.register('products', products)

In [9]:
# 4. Register with DuckDB
# create dictionary to map  table names to  DataFrames
register_dict = {
    "aisles": aisles,
    "departments": departments,
    "orders": orders,
    "products": products,
    "order_products__train": order_products__train,
    "order_products__prior": order_products__prior
}

for name, df in register_dict.items():
    duckdb.register(name, df)

#retrieve first 10 rows from products table

In [10]:

conn=duckdb.connect()
result=conn.sql("""
SELECT*
FROM products
LIMIT 10
""")
result.show()

┌────────────┬───────────────────────────────────────────────────────────────────┬──────────┬───────────────┐
│ product_id │                           product_name                            │ aisle_id │ department_id │
│   int64    │                              varchar                              │  int64   │     int64     │
├────────────┼───────────────────────────────────────────────────────────────────┼──────────┼───────────────┤
│          1 │ Chocolate Sandwich Cookies                                        │       61 │            19 │
│          2 │ All-Seasons Salt                                                  │      104 │            13 │
│          3 │ Robust Golden Unsweetened Oolong Tea                              │       94 │             7 │
│          4 │ Smart Ones Classic Favorites Mini Rigatoni With Vodka Cream Sauce │       38 │             1 │
│          5 │ Green Chile Anytime Sauce                                         │        5 │            13 │
│          6 │ Dry Nose Oil                                                      │       11 │            11 │
│          7 │ Pure Coconut Water With Orange                                    │       98 │             7 │
│          8 │ Cut Russet Potatoes Steam N' Mash                                 │      116 │             1 │
│          9 │ Light Strawberry Blueberry Yogurt                                 │      120 │            16 │
│         10 │ Sparkling Orange Juice & Prickly Pear Beverage                    │      115 │             7 │
└────────────┴───────────────────────────────────────────────────────────────────┴──────────┴───────────────┘
  10 rows                                                                                         4 columns

question 2
find all unique department names from the departments table.
#https://duckdb.org/docs/current/sql/query_syntax/select

In [11]:
duckdb.sql("""
    SELECT DISTINCT department 
    FROM departments
""").show()

┌─────────────────┐
│   department    │
│     varchar     │
├─────────────────┤
│ other           │
│ bulk            │
│ meat seafood    │
│ breakfast       │
│ canned goods    │
│ household       │
│ frozen          │
│ bakery          │
│ produce         │
│ international   │
│ pets            │
│ dry goods pasta │
│ personal care   │
│ deli            │
│ missing         │
│ alcohol         │
│ beverages       │
│ pantry          │
│ dairy eggs      │
│ snacks          │
│ babies          │
└─────────────────┘
      21 rows

#Count the total number of orders placed in the orders dataset.

In [12]:
duckdb.sql("""
    SELECT count(*)   
    FROM orders
""").show()

┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│      3421083 │
└──────────────┘

#4 list all product names found specifically in Aisle ID 61.
#documentation 
#SELECT j FROM tbl WHERE i = 3;

In [13]:
duckdb.sql("""
SELECT product_name 
FROM products
WHERE aisle_id = 61
""").show()

┌────────────────────────────────────────────────────────────┐
│                        product_name                        │
│                          varchar                           │
├────────────────────────────────────────────────────────────┤
│ Chocolate Sandwich Cookies                                 │
│ Nutter Butter Cookie Bites Go-Pak                          │
│ Danish Butter Cookies                                      │
│ Gluten Free All Natural Chocolate Chip Cookies             │
│ Mini Nilla Wafers Munch Pack                               │
│ Organic Lemon Gingersnap                                   │
│ Chips Ahoy! Chewy Cookies                                  │
│ Cookie Chips Crunchy Dark Chocolate Chocolate Chip Cookies │
│ Golden Cupcakes 8 Pack                                     │
│ Crunch Vanilla Sugar Mini Cookies                          │
│               ·                                            │
│               ·                                            │
│               ·                                            │
│ Delice Fine European Biscuits                              │
│ Pirouette Chocolate Fudge Creme Filled Wafers              │
│ Crackers, Original, Stoned Wheat                           │
│ Almond Toast Cookie                                        │
│ Hazelnut Wafers                                            │
│ Honey Snack Packs Bunny Grahams                            │
│ French Butter Cookies With Lemon & Almond                  │
│ Sandies Pecan Shortbread Cookies                           │
│ Ginger Snaps Snacking Cookies                              │
│ Famous Chocolate Wafers                                    │
└────────────────────────────────────────────────────────────┘
                     874 rows (20 shown)

#5 Display all orders sorted by the hour of the day they were placed (highest to lowest).
#Documentation
#Perform an aggregate grouped by the column i:
#SELECT i, sum(j) FROM tbl GROUP BY i;

SELECT *
FROM addresses
ORDER BY ALL DESC;

In [14]:
duckdb.sql("""
SELECT order_number
FROM orders
ORDER BY order_hour_of_day DESC
""").show()

┌────────────────────────┐
│      order_number      │
│         int64          │
├────────────────────────┤
│                     13 │
│                     90 │
│                     41 │
│                     21 │
│                     17 │
│                      3 │
│                      3 │
│                      5 │
│                     21 │
│                      5 │
│                      · │
│                      · │
│                      · │
│                      2 │
│                      2 │
│                      8 │
│                      4 │
│                     78 │
│                      6 │
│                      4 │
│                      6 │
│                     18 │
│                      2 │
└────────────────────────┘
          ? rows
  (>9999 rows, 20 shown)

In [15]:
duckdb.sql("""
    SELECT * FROM orders 
    ORDER BY order_hour_of_day DESC
""").show()

┌──────────┬─────────┬──────────┬──────────────┬───────────┬───────────────────┬────────────────────────┐
│ order_id │ user_id │ eval_set │ order_number │ order_dow │ order_hour_of_day │ days_since_prior_order │
│  int64   │  int64  │ varchar  │    int64     │   int64   │       int64       │         double         │
├──────────┼─────────┼──────────┼──────────────┼───────────┼───────────────────┼────────────────────────┤
│   720352 │    1960 │ prior    │            3 │         2 │                23 │                   11.0 │
│  2869152 │   52783 │ prior    │           11 │         2 │                23 │                    7.0 │
│  2989176 │   36781 │ prior    │            8 │         0 │                23 │                    8.0 │
│    68322 │   35038 │ prior    │           52 │         0 │                23 │                    2.0 │
│  2964033 │   52822 │ prior    │            9 │         6 │                23 │                   29.0 │
│  3057073 │   50736 │ prior    │            4 │         6 │                23 │                    2.0 │
│  1620701 │   49992 │ prior    │            3 │         1 │                23 │                   30.0 │
│   602304 │     843 │ prior    │            3 │         6 │                23 │                   30.0 │
│   861913 │   87473 │ prior    │           34 │         1 │                23 │                    5.0 │
│  2718757 │   34952 │ prior    │            5 │         4 │                23 │                    8.0 │
│      ·   │     ·   │   ·      │            · │         · │                 · │                     ·  │
│      ·   │     ·   │   ·      │            · │         · │                 · │                     ·  │
│      ·   │     ·   │   ·      │            · │         · │                 · │                     ·  │
│   540948 │  191923 │ prior    │           23 │         4 │                23 │                   12.0 │
│  2875568 │   35038 │ prior    │           24 │         5 │                23 │                    6.0 │
│   833239 │   87891 │ prior    │            4 │         5 │                23 │                   10.0 │
│  1506175 │     632 │ prior    │            5 │         6 │                23 │                   10.0 │
│  3377894 │  191890 │ prior    │            3 │         2 │                23 │                   21.0 │
│  2258646 │   87859 │ prior    │            7 │         5 │                23 │                    5.0 │
│  2778610 │   87922 │ prior    │            3 │         6 │                23 │                    6.0 │
│  1013780 │   87832 │ test     │           12 │         1 │                23 │                   30.0 │
│  2053317 │  191923 │ prior    │           26 │         1 │                23 │                    8.0 │
│  2063467 │  204818 │ prior    │           33 │         5 │                23 │                    9.0 │
└──────────┴─────────┴──────────┴──────────────┴───────────┴───────────────────┴────────────────────────┘
  ? rows (>9999 rows, 20 shown)                                                               7 columns

#alculate the total number of products associated with each department_id
#SELECT i, sum(j) FROM tbl GROUP BY i;

In [16]:
duckdb.sql("""
    SELECT count(product_name)  AS total_products
    FROM products
    GROUP BY department_id
""").show()

┌────────────────┐
│ total_products │
│     int64      │
├────────────────┤
│           6563 │
│           3449 │
│           3085 │
│           1858 │
│           1115 │
│           2092 │
│           1054 │
│           1081 │
│            548 │
│             38 │
│           6264 │
│           5371 │
│           4365 │
│           4007 │
│            972 │
│           1258 │
│            907 │
│           1684 │
│           1139 │
│           1322 │
│           1516 │
└────────────────┘
     21 rows

In [17]:
duckdb.sql("""
    SELECT department_id, COUNT(*) AS total_products
    FROM products
    GROUP BY department_id
    ORDER BY total_products DESC
""").show()

┌───────────────┬────────────────┐
│ department_id │ total_products │
│     int64     │     int64      │
├───────────────┼────────────────┤
│            11 │           6563 │
│            19 │           6264 │
│            13 │           5371 │
│             7 │           4365 │
│             1 │           4007 │
│            16 │           3449 │
│            17 │           3085 │
│            15 │           2092 │
│             9 │           1858 │
│             4 │           1684 │
│             3 │           1516 │
│            20 │           1322 │
│            21 │           1258 │
│             6 │           1139 │
│            14 │           1115 │
│            18 │           1081 │
│             5 │           1054 │
│             8 │            972 │
│            12 │            907 │
│             2 │            548 │
│            10 │             38 │
└───────────────┴────────────────┘
  21 rows              2 columns

#find the average number of days that pass between a user's orders
(days_since_prior_order)

In [18]:
duckdb.sql("""
SELECT sum(days_since_prior_order)
AS average_number_of_days_that_pass_between_a_users_orders
FROM orders;
""").show()

┌─────────────────────────────────────────────────────────┐
│ average_number_of_days_that_pass_between_a_users_orders │
│                         double                          │
├─────────────────────────────────────────────────────────┤
│                                              35732798.0 │
└─────────────────────────────────────────────────────────┘

In [19]:
duckdb.sql("""
SELECT order_number, sum(days_since_prior_order)
AS total_number_of_days_that_pass_between_a_users_orders
FROM orders
GROUP BY order_number
ORDER BY total_number_of_days_that_pass_between_a_users_orders DESC
""").show()

┌──────────────┬───────────────────────────────────────────────────────┐
│ order_number │ total_number_of_days_that_pass_between_a_users_orders │
│    int64     │                        double                         │
├──────────────┼───────────────────────────────────────────────────────┤
│            4 │                                             3181843.0 │
│            2 │                                             3163685.0 │
│            3 │                                             3152320.0 │
│            5 │                                             2700649.0 │
│            6 │                                             2319183.0 │
│            7 │                                             2011257.0 │
│            8 │                                             1757289.0 │
│            9 │                                             1550085.0 │
│           10 │                                             1373515.0 │
│           11 │                                             1210003.0 │
│            · │                                                   ·   │
│            · │                                                   ·   │
│            · │                                                   ·   │
│           92 │                                                5678.0 │
│           93 │                                                5364.0 │
│           94 │                                                5015.0 │
│           95 │                                                4814.0 │
│           96 │                                                4585.0 │
│           97 │                                                4307.0 │
│           98 │                                                3940.0 │
│           99 │                                                3940.0 │
│          100 │                                                3742.0 │
│            1 │                                                  NULL │
└──────────────┴───────────────────────────────────────────────────────┘
  100 rows (20 shown)                                        2 columns

In [20]:
duckdb.sql("""
SELECT days_since_prior_order,COUNT(*) 
AS total_number_of_days_that_pass_between_a_users_orders
FROM orders
GROUP BY days_since_prior_order
ORDER BY total_number_of_days_that_pass_between_a_users_orders DESC
""").show()

┌────────────────────────┬───────────────────────────────────────────────────────┐
│ days_since_prior_order │ total_number_of_days_that_pass_between_a_users_orders │
│         double         │                         int64                         │
├────────────────────────┼───────────────────────────────────────────────────────┤
│                   30.0 │                                                369323 │
│                    7.0 │                                                320608 │
│                    6.0 │                                                240013 │
│                    4.0 │                                                221696 │
│                    3.0 │                                                217005 │
│                    5.0 │                                                214503 │
│                   NULL │                                                206209 │
│                    2.0 │                                                193206 │
│                    8.0 │                                                181717 │
│                    1.0 │                                                145247 │
│                     ·  │                                                   ·   │
│                     ·  │                                                   ·   │
│                     ·  │                                                   ·   │
│                   18.0 │                                                 35881 │
│                   19.0 │                                                 34384 │
│                   22.0 │                                                 32012 │
│                   28.0 │                                                 26777 │
│                   23.0 │                                                 23885 │
│                   27.0 │                                                 22013 │
│                   24.0 │                                                 20712 │
│                   25.0 │                                                 19234 │
│                   29.0 │                                                 19191 │
│                   26.0 │                                                 19016 │
└────────────────────────┴───────────────────────────────────────────────────────┘
  32 rows (20 shown)                                                   2 columns

In [21]:
orders.shape

(3421083, 7)

10.4448DAYS  IE  35732798.0/3421083

In [22]:
orders.describe().T

,count,mean,std,min,25%,50%,75%,max
order_id,3421083.0,1.710542e+06,987581.739823,1.0,855271.5,1710542.0,2565812.5,3421083.0
user_id,3421083.0,1.029782e+05,59533.717794,1.0,51394.0,102689.0,154385.0,206209.0
order_number,3421083.0,1.715486e+01,17.733164,1.0,5.0,11.0,23.0,100.0
order_dow,3421083.0,2.776219e+00,2.046829,0.0,1.0,3.0,5.0,6.0
order_hour_of_day,3421083.0,1.345202e+01,4.226088,0.0,10.0,13.0,16.0,23.0
days_since_prior_order,3214874.0,1.111484e+01,9.206737,0.0,4.0,7.0,15.0,30.0

#find the average number of days that pass
between a user's orders (days_since_prior_order)
mean=1.111484e+01days

ount how many orders were placed on each day of the week (order_dow).

In [23]:
duckdb.sql("""
    SELECT order_dow, COUNT(*) AS total_orders_per_day_of_week
    FROM orders
    GROUP BY order_dow
    ORDER BY total_orders_per_day_of_week DESC
""").show()

┌───────────┬──────────────────────────────┐
│ order_dow │ total_orders_per_day_of_week │
│   int64   │            int64             │
├───────────┼──────────────────────────────┤
│         0 │                       600905 │
│         1 │                       587478 │
│         2 │                       467260 │
│         5 │                       453368 │
│         6 │                       448761 │
│         3 │                       436972 │
│         4 │                       426339 │
└───────────┴──────────────────────────────┘

In [24]:
duckdb.sql("""
SELECT order_dow, sum(order_dow)
AS total_orders_per_day_of_week
FROM orders
GROUP BY order_dow
ORDER BY total_orders_per_day_of_week DESC
""").show()

┌───────────┬──────────────────────────────┐
│ order_dow │ total_orders_per_day_of_week │
│   int64   │            int128            │
├───────────┼──────────────────────────────┤
│         6 │                      2692566 │
│         5 │                      2266840 │
│         4 │                      1705356 │
│         3 │                      1310916 │
│         2 │                       934520 │
│         1 │                       587478 │
│         0 │                            0 │
└───────────┴──────────────────────────────┘

#dentify the single busiest hour of the day for shopping based on the total number of orders.

In [25]:
duckdb.sql("""
SELECT order_hour_of_day, sum(order_hour_of_day)
AS single_most_busy_hour
FROM orders
GROUP BY order_hour_of_day
ORDER BY single_most_busy_hour DESC
""").show()

┌───────────────────┬───────────────────────┐
│ order_hour_of_day │ single_most_busy_hour │
│       int64       │        int128         │
├───────────────────┼───────────────────────┤
│                16 │               4360848 │
│                15 │               4254585 │
│                14 │               3962588 │
│                17 │               3889515 │
│                13 │               3613987 │
│                18 │               3292416 │
│                12 │               3274092 │
│                11 │               3132008 │
│                10 │               2884180 │
│                19 │               2670811 │
│                 · │                  ·    │
│                 · │                  ·    │
│                 · │                  ·    │
│                22 │               1352296 │
│                23 │                920989 │
│                 7 │                643076 │
│                 6 │                183174 │
│                 5 │                 47845 │
│                 4 │                 22108 │
│                 3 │                 16422 │
│                 2 │                 15078 │
│                 1 │                 12398 │
│                 0 │                     0 │
└───────────────────┴───────────────────────┘
  24 rows (20 shown)              2 columns

In [26]:
duckdb.sql("""
SELECT order_hour_of_day, count(*)
AS single_most_busy_hour
FROM orders
GROUP BY order_hour_of_day
ORDER BY single_most_busy_hour DESC
""").show()

┌───────────────────┬───────────────────────┐
│ order_hour_of_day │ single_most_busy_hour │
│       int64       │         int64         │
├───────────────────┼───────────────────────┤
│                10 │                288418 │
│                11 │                284728 │
│                15 │                283639 │
│                14 │                283042 │
│                13 │                277999 │
│                12 │                272841 │
│                16 │                272553 │
│                 9 │                257812 │
│                17 │                228795 │
│                18 │                182912 │
│                 · │                   ·   │
│                 · │                   ·   │
│                 · │                   ·   │
│                21 │                 78109 │
│                22 │                 61468 │
│                23 │                 40043 │
│                 6 │                 30529 │
│                 0 │                 22758 │
│                 1 │                 12398 │
│                 5 │                  9569 │
│                 2 │                  7539 │
│                 4 │                  5527 │
│                 3 │                  5474 │
└───────────────────┴───────────────────────┘
  24 rows (20 shown)              2 columns

#next question
Create a list of product names alongside their respective department names.
#join 2 tables dociumentation
#SELECT *
FROM tbl
JOIN other_table
  ON tbl.key = other_table.key;

In [27]:
duckdb.sql("""
SELECT *
FROM products 
JOIN departments
 ON products.department_id=departments.department_id

""").show()

┌────────────┬───────────────────────────────────────────────────────────────────┬──────────┬───────────────┬───────────────┬─────────────────┐
│ product_id │                           product_name                            │ aisle_id │ department_id │ department_id │   department    │
│   int64    │                              varchar                              │  int64   │     int64     │     int64     │     varchar     │
├────────────┼───────────────────────────────────────────────────────────────────┼──────────┼───────────────┼───────────────┼─────────────────┤
│          1 │ Chocolate Sandwich Cookies                                        │       61 │            19 │            19 │ snacks          │
│          2 │ All-Seasons Salt                                                  │      104 │            13 │            13 │ pantry          │
│          3 │ Robust Golden Unsweetened Oolong Tea                              │       94 │             7 │             7 │ beverages       │
│          4 │ Smart Ones Classic Favorites Mini Rigatoni With Vodka Cream Sauce │       38 │             1 │             1 │ frozen          │
│          5 │ Green Chile Anytime Sauce                                         │        5 │            13 │            13 │ pantry          │
│          6 │ Dry Nose Oil                                                      │       11 │            11 │            11 │ personal care   │
│          7 │ Pure Coconut Water With Orange                                    │       98 │             7 │             7 │ beverages       │
│          8 │ Cut Russet Potatoes Steam N' Mash                                 │      116 │             1 │             1 │ frozen          │
│          9 │ Light Strawberry Blueberry Yogurt                                 │      120 │            16 │            16 │ dairy eggs      │
│         10 │ Sparkling Orange Juice & Prickly Pear Beverage                    │      115 │             7 │             7 │ beverages       │
│          · │              ·                                                    │        · │             · │             · │     ·           │
│          · │              ·                                                    │        · │             · │             · │     ·           │
│          · │              ·                                                    │        · │             · │             · │     ·           │
│       9991 │ Stir Fry Sauce Broccoli Beef                                      │       66 │             6 │             6 │ international   │
│       9992 │ Touch Y-Peeler                                                    │       10 │            17 │            17 │ household       │
│       9993 │ Organic French Green Lentils                                      │       63 │             9 │             9 │ dry goods pasta │
│       9994 │ Light Churned Vanilla Bean                                        │       37 │             1 │             1 │ frozen          │
│       9995 │ Sesame Seed New York Style Bagels                                 │       93 │             3 │             3 │ bakery          │
│       9996 │ Less Sodium Soy Sauce                                             │       66 │             6 │             6 │ international   │
│       9997 │ Italian Style Vegetables                                          │      116 │             1 │             1 │ frozen          │
│       9998 │ Ice Cream, Natural, Vanilla Bean                                  │       37 │             1 │             1 │ frozen          │
│       9999 │ Cheese, Spreadable, Crescenza-Stracchino                          │        2 │            16 │            16 │ dairy eggs      │
│      10000 │ Refresher Strawberry Lemonade                                     │       64 │             7 │             7 │ beverages       │
└────────────┴───────────────────────────────────────────────────────────────────┴──────────┴───────────────┴───────────────┴─────────────────┘
  ? rows (>9999 rows, 20 shown)                                                                                                     6 columns

In [28]:
duckdb.sql("""
SELECT 
    products.product_name,
    products.product_id,
    departments.department
FROM products
JOIN departments
  ON products.department_id = departments.department_id
  """).show()

┌───────────────────────────────────────────────────────────────────┬────────────┬─────────────────┐
│                           product_name                            │ product_id │   department    │
│                              varchar                              │   int64    │     varchar     │
├───────────────────────────────────────────────────────────────────┼────────────┼─────────────────┤
│ Chocolate Sandwich Cookies                                        │          1 │ snacks          │
│ All-Seasons Salt                                                  │          2 │ pantry          │
│ Robust Golden Unsweetened Oolong Tea                              │          3 │ beverages       │
│ Smart Ones Classic Favorites Mini Rigatoni With Vodka Cream Sauce │          4 │ frozen          │
│ Green Chile Anytime Sauce                                         │          5 │ pantry          │
│ Dry Nose Oil                                                      │          6 │ personal care   │
│ Pure Coconut Water With Orange                                    │          7 │ beverages       │
│ Cut Russet Potatoes Steam N' Mash                                 │          8 │ frozen          │
│ Light Strawberry Blueberry Yogurt                                 │          9 │ dairy eggs      │
│ Sparkling Orange Juice & Prickly Pear Beverage                    │         10 │ beverages       │
│              ·                                                    │          · │     ·           │
│              ·                                                    │          · │     ·           │
│              ·                                                    │          · │     ·           │
│ Stir Fry Sauce Broccoli Beef                                      │       9991 │ international   │
│ Touch Y-Peeler                                                    │       9992 │ household       │
│ Organic French Green Lentils                                      │       9993 │ dry goods pasta │
│ Light Churned Vanilla Bean                                        │       9994 │ frozen          │
│ Sesame Seed New York Style Bagels                                 │       9995 │ bakery          │
│ Less Sodium Soy Sauce                                             │       9996 │ international   │
│ Italian Style Vegetables                                          │       9997 │ frozen          │
│ Ice Cream, Natural, Vanilla Bean                                  │       9998 │ frozen          │
│ Cheese, Spreadable, Crescenza-Stracchino                          │       9999 │ dairy eggs      │
│ Refresher Strawberry Lemonade                                     │      10000 │ beverages       │
└───────────────────────────────────────────────────────────────────┴────────────┴─────────────────┘
  ? rows (>9999 rows, 20 shown)                                                          3 columns

#Retrieve a list showing order_id and the names of the products #contained in each order.

In [29]:
duckdb.sql("""
SELECT 
    orders.order_id,
    products.product_name
FROM orders
JOIN products
  ON orders.order_id = products.product_id
  """).show()

┌──────────┬──────────────────────────────────────────────────────────────┐
│ order_id │                         product_name                         │
│  int64   │                           varchar                            │
├──────────┼──────────────────────────────────────────────────────────────┤
│    23391 │ Organic Fennel Bulb                                          │
│    19256 │ Belgian Chocolate Chocolate Ice Cream                        │
│     8382 │ Organic Tomato Bisque                                        │
│     7099 │ Sleepytime Vanilla Caffeine Free Herbal Tea Bags             │
│    14400 │ Spray Gel, Citrus Scent                                      │
│    19190 │ Curved Panty Liners                                          │
│    31801 │ 9 Inch Plates                                                │
│    39325 │ Unscented Bubble Bath                                        │
│    13318 │ Organic YoToddler Pouch Pear Spinach Mango Yogurt            │
│    48293 │ Swiss Dark Chocolate with Honey & Almond Nougat Candy        │
│      ·   │                     ·                                        │
│      ·   │                     ·                                        │
│      ·   │                     ·                                        │
│    14982 │ Chocolate Peanut Mini Snack Nutrition Bars                   │
│    17889 │ Caramel Vanilla Cream Light Roast K-Cup Packs Arabica Coffee │
│    12054 │ Lemon Sparkling Soda                                         │
│    46563 │ Bruschetta, with Italian Basil                               │
│     6453 │ V Fusion Cranberry Blackberry                                │
│    18325 │ Classic Meal For 2 Chicken Alla Vodka & Farfalle             │
│    40270 │ Cavity Defense Medium Toothbrush                             │
│    36661 │ Men's One Daily Vegetarian Tablet                            │
│     9131 │ All Occasion Napkins 2-Ply Premium                           │
│     4478 │ Chocolate Fudge Brownie Frozen Yogurt                        │
└──────────┴──────────────────────────────────────────────────────────────┘
  ? rows (>9999 rows, 20 shown)                                 2 columns

#List all products and the name of the aisle they belong to.

In [30]:
duckdb.sql("""
SELECT 
    aisles.aisle_id,
    products.product_name
FROM aisles
JOIN products
  ON aisles.aisle_id = products.product_id
  """).show()

┌──────────┬───────────────────────────────────────────────────────────────────┐
│ aisle_id │                           product_name                            │
│  int64   │                              varchar                              │
├──────────┼───────────────────────────────────────────────────────────────────┤
│        1 │ Chocolate Sandwich Cookies                                        │
│        2 │ All-Seasons Salt                                                  │
│        3 │ Robust Golden Unsweetened Oolong Tea                              │
│        4 │ Smart Ones Classic Favorites Mini Rigatoni With Vodka Cream Sauce │
│        5 │ Green Chile Anytime Sauce                                         │
│        6 │ Dry Nose Oil                                                      │
│        7 │ Pure Coconut Water With Orange                                    │
│        8 │ Cut Russet Potatoes Steam N' Mash                                 │
│        9 │ Light Strawberry Blueberry Yogurt                                 │
│       10 │ Sparkling Orange Juice & Prickly Pear Beverage                    │
│        · │                       ·                                           │
│        · │                       ·                                           │
│        · │                       ·                                           │
│      125 │ Herbal Armor DEET-Free Natural Insect Repellant                   │
│      126 │ Hot & Spicy Chicken Flavor Ramen Noodles                          │
│      127 │ Marscapone                                                        │
│      128 │ Organic Wild Blueberries                                          │
│      129 │ Traditional Chicken & Orzo with Lemon Soup                        │
│      130 │ Vanilla Milk Chocolate Almond Ice Cream Bars Multi-Pack           │
│      131 │ Brioche Bachelor Loaf                                             │
│      132 │ Yogurt Strawberry Pomegranate                                     │
│      133 │ Purifying Daily Detox Scrub                                       │
│      134 │ Stain Release Boost In-Wash Stain Remover Pacs                    │
└──────────┴───────────────────────────────────────────────────────────────────┘
  134 rows (20 shown)                                                2 columns

#Display user_id, order_id, and product_name 
#for the first 20 records in the dataset.

In [31]:
duckdb.sql("""
SELECT 
    orders.order_id,
    products.product_name,
    orders.user_id
FROM orders
JOIN products
  ON orders.order_id = products.product_id
  """).show()

┌──────────┬─────────────────────────────────────────────────────────────┬─────────┐
│ order_id │                        product_name                         │ user_id │
│  int64   │                           varchar                           │  int64  │
├──────────┼─────────────────────────────────────────────────────────────┼─────────┤
│    22918 │ Praline Chocolate Bar                                       │   18589 │
│    31965 │ Ezekiel 4:9 Sprouted Golden Flax Waffles  6 Count           │   18589 │
│    43293 │ Fruit by the Foot Strawberry Fruit Flavored Snacks          │   18591 │
│    33853 │ Complete ActionPacs Clorox Fresh Scent Dishwasher Detergent │   18603 │
│     1559 │ Cherry Pomegranate Greek Yogurt                             │   18606 │
│    18210 │ Men Refreshing Splash Body Wash                             │   18607 │
│     3287 │ Security Super Plus Tampons                                 │   18631 │
│     1875 │ To Go Creamy Peanut Butter Cups                             │   18632 │
│    22555 │ Low Sodium Borscht                                          │   18632 │
│    27535 │ Sunchips Sweet And Spicy Bbq 10.5oz                         │   18632 │
│       ·  │           ·                                                 │     ·   │
│       ·  │           ·                                                 │     ·   │
│       ·  │           ·                                                 │     ·   │
│     4154 │ Savory Vegetable Soup                                       │   53936 │
│    45778 │ Kitchen Bags, Compactor, with Key-Lock Closures, 18 Gallon  │   53945 │
│    29112 │ Organic Spicy Chili                                         │   53948 │
│      174 │ Vanishing Acne Treatment Cream                              │   53965 │
│     6362 │ Sea Algae Serum                                             │   53967 │
│    20535 │ Organic Portabella Mushrooms                                │   53973 │
│    14121 │ Organic Yo Kids Squeezers                                   │   53976 │
│    13399 │ Organic Hard Candies Ginger                                 │   53981 │
│     3189 │ Caramel Lovers Variety Candy Bars                           │   53982 │
│    32649 │ Organic Watermelon Cream Soda                               │   53986 │
└──────────┴─────────────────────────────────────────────────────────────┴─────────┘
  ? rows (>9999 rows, 20 shown)                                          3 columns

#first20
#select sample of 10 rows


Join two tables together:

SELECT *
FROM tbl
JOIN other_table
  ON tbl.key = other_table.key;

Select a 10% sample from a table:

SELECT *
FROM tbl
TABLESAMPLE 10%;

Select a sample of 10 rows from a table:

SELECT *
FROM tbl
TABLESAMPLE 10 ROWS;

In [32]:
duckdb.sql("""
SELECT 
    orders.order_id,
    products.product_name,
    orders.user_id
FROM orders
JOIN products
TABLESAMPLE 20 ROWS
  ON orders.order_id = products.product_id
  """).show()

┌──────────┬──────────────────────────────────────────────────────────────┬─────────┐
│ order_id │                         product_name                         │ user_id │
│  int64   │                           varchar                            │  int64  │
├──────────┼──────────────────────────────────────────────────────────────┼─────────┤
│    10154 │ Gold S'mores                                                 │   31471 │
│    13331 │ Organics Chocolate Chip Organic Cookie Mix                   │   31606 │
│    15095 │ Kettle Cooked Potato Chips Original (15 Oz)                  │   34546 │
│    12527 │ Sidecar Orange Pale Ale                                      │   86947 │
│    38949 │ Febreze Fresh Clean Garbage Bags                             │   91502 │
│    35631 │ Southern Pecan Ice Cream                                     │  114977 │
│    14757 │ 4T to 5T Pull Ups Training Pants                             │  161131 │
│    22873 │ Grass Fed Vat Unsalted Cultured Butter                       │  189009 │
│    26963 │ Real Ice Cream Pistachio                                     │   23455 │
│    19423 │ Nature's Colors Decorating Set                               │   92799 │
│    24925 │ Mint Chocolate Chip Frozen Greek Yogurt Bars                 │  144086 │
│    23458 │ Creamy milk chocolate with crisped rice. Chocolate Candy bar │   13674 │
│    38485 │ Cheese Dippers                                               │   59098 │
│    31821 │ Cubanelle Pepper                                             │  104556 │
│     1110 │ Broccoli Carrots Sugar Snap Peas & Water Chestnuts           │  106082 │
│    21332 │ Organic Hom Mali Jasmine Rice                                │  181788 │
│    46703 │ Shelled Soybeans Edamame                                     │   28371 │
│    47985 │ Baking & Drinking Wondercocoa                                │  149787 │
│    41027 │ Original Crackerbread Hearts                                 │  199004 │
│    30409 │ Gallon Size with Ties Storage Bags                           │  200826 │
└──────────┴──────────────────────────────────────────────────────────────┴─────────┘
  20 rows                                                                 3 columns

In [33]:
duckdb.sql("""
SELECT 
    orders.order_id,
    products.product_name,
    orders.user_id
FROM orders
JOIN products
  ON orders.order_id = products.product_id
   LIMIT 20 
  """).show()

┌──────────┬──────────────────────────────────────────────────────────────────┬─────────┐
│ order_id │                           product_name                           │ user_id │
│  int64   │                             varchar                              │  int64  │
├──────────┼──────────────────────────────────────────────────────────────────┼─────────┤
│    22057 │ Awesome Paper Towel Towel                                        │   12386 │
│    26565 │ Super Glue 2 Pack                                                │   12386 │
│     2638 │ Steak Eater's Burgers                                            │   12394 │
│    25699 │ Artisan Thin Pizza Crust Rosemary & Olive Oil Flatbread          │   12395 │
│    12420 │ 100% Lactose Free 1% Milkfat Chocolate Lowfat Milk               │   12407 │
│     1778 │ Pull-Ups Night‑Time Training Pants 2T‑3T                         │   12407 │
│    41904 │ Kefir, Organic, Mango, Orange & Pineapple                        │   12411 │
│    49412 │ Original Cashew Milk                                             │   12413 │
│     5680 │ All Natural Homogenized Vitamin D Milk                           │   12424 │
│    31954 │ Broccoli Slaw                                                    │   12430 │
│    18697 │ Gillette Fusion ProGlide Sensitive 2 in 1 Shave Gel Ocean Breeze │   12433 │
│    10447 │ Pearled Barley                                                   │   12433 │
│    33072 │ Cheese, Asiago                                                   │   12435 │
│    45175 │ Oregano Oil, Standardized, Liquid Vcaps                          │   12445 │
│      686 │ Tea Tree + Sea Buckthorn Calming Shampoo                         │   12445 │
│    11229 │ Spinach Veggie Dip                                               │   12446 │
│     8880 │ Supreme Supper Classic Pate Cat Food                             │   12446 │
│    28916 │ Hot House Seedless Cucumbers                                     │   12450 │
│    35878 │ Traditional Pumpkin Pie 6''                                      │   12457 │
│    38662 │ Roasted Almond Butter                                            │   12461 │
└──────────┴──────────────────────────────────────────────────────────────────┴─────────┘
  20 rows                                                                     3 columns

duckdb.sql(""" SELECT orders.user_id, .order_id, product_info.product_name FROM orders JOIN products ON orders.order_id = products.order_id JOIN product_info ON products.product_id = product_info.product_id LIMIT 20 """).show()

Find the top 5 most popular products based on the number of times they appear in the order_products table.

find the top 5 most popular products based on the number of times they appear in the order_products table. 

#using order_products__prior & order_products__train

In [34]:
duckdb.sql("""
SELECT 
    products.product_name,
    COUNT(op.product_id) AS times_ordered
FROM (
    SELECT * FROM order_products__prior
    UNION ALL
    SELECT * FROM order_products__train
) AS op
JOIN products
  ON op.product_id = products.product_id
GROUP BY products.product_name
ORDER BY times_ordered DESC
LIMIT 5;
""").show()

┌────────────────────────┬───────────────┐
│      product_name      │ times_ordered │
│        varchar         │     int64     │
├────────────────────────┼───────────────┤
│ Banana                 │        491291 │
│ Bag of Organic Bananas │        394930 │
│ Organic Strawberries   │        275577 │
│ Organic Baby Spinach   │        251705 │
│ Organic Hass Avocado   │        220877 │
└────────────────────────┴───────────────┘

dentify the top 10 users who have placed the highest number of total orders.

In [35]:
duckdb.sql("""
SELECT 
    user_id,
    COUNT(order_id) AS total_orders
FROM orders
GROUP BY user_id
ORDER BY total_orders DESC
LIMIT 10;
""").show()

┌─────────┬──────────────┐
│ user_id │ total_orders │
│  int64  │    int64     │
├─────────┼──────────────┤
│   12166 │          100 │
│   33934 │          100 │
│   53684 │          100 │
│    9682 │          100 │
│   51072 │          100 │
│   10046 │          100 │
│   54259 │          100 │
│    9513 │          100 │
│   50024 │          100 │
│   54594 │          100 │
└─────────┴──────────────┘
  10 rows      2 columns

tegorize orders into 'Weekend' (Days 0 and 1) vs 'Weekday' (Days 2-6) and count the total
orders for each category

https://duckdb.org/docs/current/sql/expressions/case?utm_source=copilot.com


#syntax
CREATE OR REPLACE TABLE integers AS SELECT unnest([1, 2, 3]) AS i;
SELECT i, CASE i WHEN 1 THEN 10 WHEN 2 THEN 20 WHEN 3 THEN 30 END AS test
FROM integers;

In [36]:
duckdb.sql("""
SELECT 
    CASE 
        WHEN order_dow IN (0,1) THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_category,
    COUNT(order_id) AS total_orders
FROM orders
GROUP BY day_category
ORDER BY day_category;
""").show()

┌──────────────┬──────────────┐
│ day_category │ total_orders │
│   varchar    │    int64     │
├──────────────┼──────────────┤
│ Weekday      │      2232700 │
│ Weekend      │      1188383 │
└──────────────┴──────────────┘

4 d the top 5 products that are most frequently added to the cart first (where 
add_to_cart_order = 1)

In [37]:
duckdb.sql("""
SELECT 
    products.product_name,
    COUNT(op.product_id) AS first_added_count
FROM (
    SELECT * FROM order_products__prior
    UNION ALL
    SELECT * FROM order_products__train
) AS op
JOIN products
  ON op.product_id = products.product_id
WHERE op.add_to_cart_order = 1
GROUP BY products.product_name
ORDER BY first_added_count DESC
LIMIT 5;
""").show()

┌────────────────────────┬───────────────────┐
│      product_name      │ first_added_count │
│        varchar         │       int64       │
├────────────────────────┼───────────────────┤
│ Banana                 │            115521 │
│ Bag of Organic Bananas │             82877 │
│ Organic Whole Milk     │             32071 │
│ Organic Strawberries   │             28875 │
│ Organic Hass Avocado   │             24913 │
└────────────────────────┴───────────────────┘

Calculate the overall reorder rate (the average of the reordered column)

In [38]:
duckdb.sql("""
SELECT 
    AVG(reordered) AS overall_reorder_rate
FROM order_products__train;
""").show()

┌──────────────────────┐
│ overall_reorder_rate │
│        double        │
├──────────────────────┤
│   0.5985944127509629 │
└──────────────────────┘