In [1]:
import pandas as pd
import numpy as np

In [2]:
v=pd.read_csv(r'\Users\DELL\Downloads\archive\housing_price_dataset.csv')
v

       SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
0            2126         4          1        Rural       1969  215355.283618
1            2459         3          2        Rural       1980  195014.221626
2            1860         2          1       Suburb       1970  306891.012076
3            2294         2          1        Urban       1996  206786.787153
4            2130         5          2       Suburb       2001  272436.239065
...           ...       ...        ...          ...        ...            ...
49995        1282         5          3        Rural       1975  100080.865895
49996        2854         2          2       Suburb       1988  374507.656727
49997        2979         5          3       Suburb       1962  384110.555590
49998        2596         5          2        Rural       1984  380512.685957
49999        1572         5          3        Rural       2011  221618.583218

[50000 rows x 6 columns]

read the data --change column names
describe\know the data 
-describe
.shape
-.correlation(Num)
clean the data 
fill nana(0)-.Num
fill cAT WITHH MODE
DROP DUPLICATES
ENCODE


FEATure engineering
encode
into newcolumns
drop irrelevant columns 

chart ---matplotlib
chart--seaborn

method chaining avoids spap=ghetti 

achieved by wrapping operations
in a chain every function returns new DataFrame 

final_report=(df
.query('Sales>100')
.rename(columns={'Sales'

In [3]:
v=pd.read_csv(r'\Users\DELL\Downloads\archive\housing_price_dataset.csv')
v

       SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
0            2126         4          1        Rural       1969  215355.283618
1            2459         3          2        Rural       1980  195014.221626
2            1860         2          1       Suburb       1970  306891.012076
3            2294         2          1        Urban       1996  206786.787153
4            2130         5          2       Suburb       2001  272436.239065
...           ...       ...        ...          ...        ...            ...
49995        1282         5          3        Rural       1975  100080.865895
49996        2854         2          2       Suburb       1988  374507.656727
49997        2979         5          3       Suburb       1962  384110.555590
49998        2596         5          2        Rural       1984  380512.685957
49999        1572         5          3        Rural       2011  221618.583218

[50000 rows x 6 columns]

In [4]:
v.describe()

         SquareFeet      Bedrooms     Bathrooms     YearBuilt          Price
count  50000.000000  50000.000000  50000.000000  50000.000000   50000.000000
mean    2006.374680      3.498700      1.995420   1985.404420  224827.325151
std      575.513241      1.116326      0.815851     20.719377   76141.842966
min     1000.000000      2.000000      1.000000   1950.000000  -36588.165397
25%     1513.000000      3.000000      1.000000   1967.000000  169955.860225
50%     2007.000000      3.000000      2.000000   1985.000000  225052.141166
75%     2506.000000      4.000000      3.000000   2003.000000  279373.630052
max     2999.000000      5.000000      3.000000   2021.000000  492195.259972

In [5]:
v.shape()

TypeError: 'tuple' object is not callable

In [6]:
v.shape

(50000, 6)

In [7]:
v.isnull().sum()

SquareFeet      0
Bedrooms        0
Bathrooms       0
Neighborhood    0
YearBuilt       0
Price           0
dtype: int64

In [13]:
v=(v
   .assign(
       price_per_sqft=lambda x: x["Price"] cx["SquareFeet"],
        house_age=lambda x: 2026-x["YearBuilt"]
     ))  
v.head ()

,SquareFeet,Bedrooms,Bathrooms,Neighborhood,YearBuilt,Price,price_per_sqft,house_age
0,2126,4,1,Rural,1969,215355.283618,101.295994,57
1,2459,3,2,Rural,1980,195014.221626,79.306312,46
2,1860,2,1,Suburb,1970,306891.012076,164.995168,56
3,2294,2,1,Urban,1996,206786.787153,90.142453,30
4,2130,5,2,Suburb,2001,272436.239065,127.904338,25

In [17]:
v["price_per_square_foot"]=v["Price"]/ v["SquareFeet"]
v.head()

,SquareFeet,Bedrooms,Bathrooms,Neighborhood,YearBuilt,Price,price_per_sqft,house_age,price_per_square_foot
0,2126,4,1,Rural,1969,215355.283618,101.295994,57,101.295994
1,2459,3,2,Rural,1980,195014.221626,79.306312,46,79.306312
2,1860,2,1,Suburb,1970,306891.012076,164.995168,56,164.995168
3,2294,2,1,Urban,1996,206786.787153,90.142453,30,90.142453
4,2130,5,2,Suburb,2001,272436.239065,127.904338,25,127.904338

spahetti marcaroni hihlighted above for a new column price per square feet in attempt ot find medium cheapest neihborhood 

functonal programming is method chining
.drop_duplicates()
.dropna()

spaghetti is cell by cell
2nd way write functions functional proramming

DONT USE MARCARONI FOR THE ASSIGNMENT
USE CELL BY CELL FOR THE NEXT ASSIGNMENT
DO THE ASSIGNMEMT
END TO END

In [19]:
v=(v
   .assign(
       price_per_sqft=lambda x: x["Price"]/ x["SquareFeet"],
        house_age=lambda x: 2026-x["YearBuilt"]
     )
  .groupby("Neighborhood")["price_per_sqft"]
    .mean()
  ) 
v.head ()

Neighborhood
Rural     113.244352
Suburb    112.802822
Urban     113.871817
Name: price_per_sqft, dtype: float64

In [26]:
v=(v
   .dropna()
   .drop_duplicates()
   .astype({"Price':int,"SquareFeet":int,"YearBuilt":int})
   .assign(
       price_per_sqft=lambda x: x["Price"]/ x["SquareFeet"],
       house_age=lambda x: 2026-x["YearBuilt"]
     )
   .groupby("Neighborhood")["price_per_sqft"]
   .mean()
  ) 
v.head ()

SyntaxError: unterminated string literal (detected at line 4) (4288284086.py, line 4)